### ISSUE TITLE
Please keep your former projects privately or delete them

### ISSUE THREAD

**Issue by emilygrande** [eternalwaves/Bee-Curious-LMS#1]
Hi, this is emily, TA for MET CS program.

Could you please keep your former projects privately or delete them ? I am afraid that someone has used your code for their projects...

Thanks a lot !

**Comment by eternalwaves** [comment]
Hi Emily,

I haven't updated this repository in a while, but have kept a public Github
portfolio for many years before I started the BU MET CS program. I do
intend to refine this project, specifically, for open-source use and as
part of my (public) code portfolio for employers. I started as a designer
but turned developer almost a decade ago. The only work I can use to
demonstrate my abilities are personal projects and open-source
contributions, as for most other work I sign NDAs with clients. Are you
saying I need to hide my work because someone else can't do their own?

## Elizabeth Lynn Rakphongphairoj Kilrain

_Beehive.codes https://beehive.codesGithub
https://github.com/eternalwaves/_

**Comment by emilygrande** [comment]
sorry to bother you.. I just found more than 2 people have similar code as
yours...  I hope my students can do their own...

Thanks a lot !  Appreciate it !

On Wed, May 25, 2016 at 1:20 PM, Elizabeth Kilrain <notifications@github.com

**Comment by eternalwaves** [comment]
Emily, this is not my responsibility. In development, we will not always reinvent the wheel because there are coding best practices, and someone else may have done it better and more succinctly. If you feel that their conduct is beyond a reasonable limit, i.e., they used not only examples but full structures and ideas, please take action in compliance with BU's Academic Conduct policies.

I am closing this issue.
